language: objective-c
osx_image: xcode11.2

env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone X'
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone 8'

script:
  - xcodebuild clean build test -project "M7UIKit.xcodeproj" -scheme M7UIKit -sdk $TEST_SDK ONLY_ACTIVE_ARCH=NO | xcpretty
