language: objective-c
osx_image: xcode11.2

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project "M7UIKit.xcodeproj" -scheme M7UIKit -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO | xcpretty
