language: objective-c
osx_image: xcode11.2
before_install:
  - gem install cocoapods --pre
xcode_workspace: M7UIKit.xcworkspace
xcode_scheme: M7UIKitExamples
script: set -o pipefail && xcodebuild test -workspace M7UIKit.xcworkspace -scheme M7UIKitExamples|xcpretty
