language: objective-c
osx_image: xcode11.3

script:
- xcodebuild clean build test -project "M7UIKit.xcodeproj" -scheme M7UIKit -sdk iphonesimulator13.2 -destination "OS=13.2,name=iPhone X" ONLY_ACTIVE_ARCH=NO
