on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: |
          xcodebuild clean test -project M7UIKit.xcodeproj -scheme M7UIKit -destination "${destination}" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
