name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: aromanov91/M7UIKit@master
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
