on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X','platform=iOS Simulator,OS=13.1,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild clean build test -project "M7UIKit.xcodeproj" -scheme M7UIKit -sdk $TEST_SDK ONLY_ACTIVE_ARCH=NO | xcpretty
        env: 
         destination: ${{ matrix.destination }}
